export const currency = '$';
export const currentYear = new Date().getFullYear();
export const developedByLink = 'https://www.e-rx.co.za/index.php/';
export const developedBy = ' ERX Solutions Pvt Ltd';
export const contactUs = 'engrharisshah1122@gmail.com';
export const buyLink = '';
export const basePath = '';
export const DEFAULT_PAGE_TITLE = 'Reback React | Responsive Admin Dashboard Template';
export const colorVariants = ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'dark', 'purple', 'pink', 'orange', 'light', 'link'];